# Site settings
title: Piyush's Notes
email: piyushahuja.in@gmail.com
description: "Some passably good ideas" #First, it is good to include a short meta description in the <head> tag of your page, as Google will display that under the link to your site in the search results
baseurl: ""
url: "http://piyushahuja.com"
author: Piyush Ahuja


# Build settings
markdown: kramdown
permalink: pretty

# disqus:
#     shortname: 'piyushahuja'

# pages_list:       
#   About: '/about'
#   Archive: '/archive'
#   Feed: '/atom.xml
#   
#   
# I nlayours: <h3 class="masthead-title">
# <a href="/" title="Home">{{ site.title }}</a>

# {% for page in site.pages_list %}
#   &nbsp;&nbsp;&nbsp;
#   <small><a href="{{ page[1]  }}">{{ page[0] }}</a></small>
# {% endfor %}
# </h3>
